// auto generated by go tool dist

package objabi

import "runtime"

const defaultGOROOT = `/usr/local/go`
const defaultGO386 = `sse2`
const defaultGOARM = `7`
const defaultGOOS = runtime.GOOS
const defaultGOARCH = runtime.GOARCH
const defaultGO_EXTLINK_ENABLED = ``
const version = `devel +286599f270 Tue Jul 11 18:32:56 2017 +0000`
const stackGuardMultiplier = 1
const goexperiment = ``
